react-icons/react-icons

- README.md
Please let me know if you would like spellchecks to be separated from rephrasing in the commits.
Thanks!
> Improve consistency in wording and spellcheck

- package.json
Everything is working with react 15. Just updated the peerDependencies to remove warnings.
Closes issue #22
> updated peer dependencies

- package.json
Hey @gorangajic thanks for building this. It's been a wonderful resource for me and my projects. And thank you for allowing me to contribute!
> bump react-icon-base version

- bin/create.js
https://facebook.github.io/react/docs/reusable-components.html#stateless-functions
Benefit : less code generated in lib (no need for classes, extends)
> Use Stateless Functions

- bin/create.js
I'm wondering if this change would break things for people. It works on my projects, but I'm using nearly the same setup on all projects.
> Re: Use Stateless Functions; Replace require with import.

- README.md
See: https://github.com/gorangajic/react-icons/issues/85
> Document workaround with Create-React-App

- README.md
Based on last comment from here https://github.com/gorangajic/react-icons/issues/56
> path change in usage example

- .npmignore
sometimes i need the svg for background, is this acceptable?
> Publish icons folder

- README.md
- packages/demo/src/App.js
- packages/react-icons/package.json
- packages/react-icons/src/iconBase.tsx
- packages/react-icons/src/iconContext.tsx
- ref #165 
- new context api options
> add attr option in context api

- packages/preview/src/App.css
Added small UX improvement, now it's more simple to select and copy icon name. 
[Video preview](https://monosnap.com/file/bDVoqE7EOTObZpzSQFFdV1Pk1zhEBz)
> Added 'user-select: all' to the icon names

- packages/react-icons/src/iconBase.tsx
> Remove IconBase attr prop from props passed to svg

- .gitmodules
- README.md
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/src/icons/index.js
Added svg game icons from https://game-icons.net
https://react-icons-gi.surge.sh/#/icons/gi
> Added Game Icons

- .gitmodules
- README.md
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/src/icons/index.js
Added Weather Icons from https://erikflowers.github.io/weather-icons/
> Added Weather Icons

- packages/react-icons/scripts/build.js
> :bug: Use var instead of const.

- packages/preview/src/App.css
- packages/preview/src/App.js
Created a new navlink with an input for search query and a new route to for a result display across all icon sets.
> Add ability to search icons

- .gitmodules
- .travis.yml
- build-script.sh
- package.json
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/src/icons/index.js
- fix travis build script. must use bash.
- rename ant design icons id.
- not use `--recursive` in git submodule update
> fix ci builds

- packages/preview/package.json
- packages/preview/src/App.js
- packages/preview/src/pages/iconset/index.js
- packages/preview/src/pages/search/index.js
- packages/preview/src/pages/search/search-results.js
- packages/preview/src/utils.js
- yarn.lock
https://github.com/kentcdodds/babel-plugin-codegen
> preview: optimize dynamic import

- packages/react-icons/scripts/build.js
This PR solve issue #235 related to missing entry point with node (react SSR)
> fix(build): add entry point. Solve issue #235

- packages/preview/src/components/@core/sidebar/index.tsx
- packages/preview/src/components/pages/search/index.tsx
- packages/preview/src/components/pages/search/search-iconset.tsx
- packages/preview/src/utils/search-context.tsx
> Add "No icons found" message when no icons are found

- .gitmodules
- README.md
- packages/demo/src/App.js
- packages/demo/src/__snapshots__/App.test.js.snap
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/src/icons/index.js
Added Grommet-Icons from https://github.com/grommet/grommet-icons
> Added grommet-icons library to react-icons

- .gitmodules
- README.md
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/VERSIONS
- packages/react-icons/scripts/build.js
- packages/react-icons/src/icons/index.js
Fixes https://github.com/react-icons/react-icons/issues/296
> add vscode icons

- .gitmodules
- README.md
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/VERSIONS
- packages/react-icons/scripts/build.js
- packages/react-icons/src/icons/index.js
Add [css.gg](https://css.gg/) icons
https://github.com/astrit/css.gg/tree/master/icons/svg
https://react-icons-custom.onurgvnc.vercel.app
Closes #277
> Add css.gg icons

- .gitmodules
- README.md
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/VERSIONS
- packages/react-icons/src/icons/index.js
Closes #298
https://react-icons-custom.onurgvnc.vercel.app
> Add BoxIcons

- .gitmodules
- README.md
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/VERSIONS
- packages/react-icons/src/icons/index.js
https://github.com/Keyamoon/IcoMoon-Free
https://github.com/Keyamoon/IcoMoon-Free/tree/master/SVG
https://react-icons-custom.onurgvnc.vercel.app/
> add icomoon-free

- .gitmodules
- README.md
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/VERSIONS
- packages/react-icons/src/icons/index.js
PR to add [Simple Icons](https://simpleicons.org/) v2.13.0
Used the build script to test locally, seems to work quite well.
> Add simple icons

- .gitmodules
- packages/react-icons/.gitignore
- packages/react-icons/LICENSE
- packages/react-icons/VERSIONS
- packages/react-icons/src/icons/index.js
https://heroicons.dev/
https://github.com/refactoringui/heroicons
https://react-icons-custom.onurgvnc.vercel.app/
> add heroicons

- packages/react-icons/scripts/build.js
Related to my comment https://github.com/react-icons/react-icons/issues/154#issuecomment-622986959
> Remove displayName in favor of function name

- packages/react-icons/scripts/logics.js
> remove pid svg attrbutes

- README.md
heroicon is been included.
close #356 
close #332
> update icons list in readme.md

- README.md
In this pull-request, i only change doc in readme from ReactJs Class Component to React Functional Component that is mostly used for developers.
> Change readme from class to functional components

- .gitmodules
- README.md
- packages/react-icons/VERSIONS
- packages/react-icons/src/icons/index.js
This pull request adds "Simple Line Icons" to the package.
> Add Simple Line Icons to icon set

- packages/react-icons/scripts/logics.ts
> fix: invalid data prop react-icons/ci

- packages/react-icons/VERSIONS
- packages/react-icons/package.json
- packages/react-icons/src/icons/index.ts
- yarn.lock
Updated GitHub octicons to new package
> feat: updated octicons

- packages/preview-astro/package.json
- packages/preview-astro/src/components/search/index.tsx
- packages/preview-astro/src/components/searchinput.tsx
- packages/preview-astro/src/layouts/Layout.astro
- packages/preview-astro/src/store/store.tsx
- packages/preview-astro/src/utils/usesearch.tsx
- yarn.lock
- ref #841
- Resolved a problem with the search box losing focus when moving from one screen to another.
- Use nanostores to save search word state
> astro: Keep focus search input in sidebar

- build-script.sh
- packages/demo-all-files/package.json
- packages/demo/package.json
- packages/react-icons/VERSIONS
- packages/react-icons/package.json
- packages/react-icons/scripts/_global.d.ts
- packages/react-icons/scripts/_types.ts
- packages/react-icons/scripts/build.ts
- packages/react-icons/scripts/logics.ts
- packages/react-icons/scripts/svgo.ts
- packages/react-icons/scripts/task_all.ts
- packages/react-icons/scripts/task_common.ts
- packages/react-icons/scripts/task_files.ts
- packages/react-icons/scripts/templates.ts
- packages/react-icons/scripts/tsconfig.json
- yarn.lock
* update cheerio svgo
* add type annotations
> update cheerio, svgo 

- packages/preview-astro/src/store/store.tsx
- packages/preview-astro/src/utils/usesearch.tsx
Just fixing a small typo from `serachWord` to `searchWord`.
> Fix typo on store.tsx

- packages/react-icons/VERSIONS
- packages/react-icons/src/icons/index.ts
> change boxicons license

- packages/react-icons/scripts/logics.ts
> remove title tag

- packages/react-icons/scripts/task_all.ts
> fix typescript definition

- packages/preview-astro/src/components/icondetailmodal.tsx
- packages/preview-astro/src/styles/_components.scss
I was using the react icons and noticed some things that I believe could be better.
This is my first attempt at contributing with react icons, forgive me if I have violated any rules
1 - A hook was added that allows a smooth opening and closing animation of the modal.
Basically the hook listens for changes in isOpen, which is the main controller for saying whether the modal is open or closed.
When isOpen is true, the hook also sets AnimationIsOpen to true, to update the right from -600px to 0px, this opens the modal.
When a closing event happens, then the closing animation is started, and after 250ms, which is the animation time, then onClose is effectively called to close the modal.
Such adjustments give the impression of opening and closing the modal.
Video, before and now …
> Add smooth animation when displaying icon details and improve mobile responsive

- packages/preview-astro/src/components/search/index.tsx
- packages/preview-astro/src/components/search/search-iconset.tsx
To search for multiple words, separate them with a space. Highlighting also works with multiple words.
fix #859 #633
close #621 #860 #636
> preview site: multiword search

- packages/react-icons/src/icons/index.ts
> Update Simple Icons version in index.ts

- packages/react-icons/scripts/logics.ts
> remove data-* attributes

- packages/react-icons/VERSIONS
- packages/react-icons/src/icons/index.ts
> icons version up 2024-04-30

- packages/react-icons/src/icons/index.ts
> bug fix: add filled suffix in tb
