react-icons/react-icons

bin/create.js

Fixing #75 by exporting a named function rather than an anonymous one in each build component.

Export named functions instead of anonymous

---

package.json

Upgrading to react 15.5 causes the proptypes warning to throw. Using CRA, this fails tests. `react-icon-base` has been updated to reflect this, but a `yarn add react-icons` is still installing `2.0.4`

Update react-icon-base to 2.0.5

---

README.md

I want to offer tool [Icon Viewer](https://andy-pro.github.io/icon-viewer) , that allows you to quickly find the necessary icon and copy its svg-code.

add link to Icon Viewer

---

package.json

We are not able to use npm shrinkwrap because of this "react": "^0.14.0 || ^15.0.0" dependency in our project. It seems like react-icons wokrs good with React 16.0

Update package.json peer dependency to React v16.0

---

package.json

Upgrade it to latest version.
Changelog: https://github.com/gorangajic/react-icon-base/compare/f513a09649b3cccf7ff08f60e2a40e9e0ef0e758...863b88117916aea71f330659da6ba7f9720c8154
No feature change but fixes the packaging around `prop-types` dependency.
This fix the installation of `react-icons` for project already requiring a locked version of `prop-types`.

Upgrade react-icon-base to 2.1.0

---

README.md

Corrects all icons (*) import path.
Provides a usage example for a specific icon when all icons were imported.

Improve all icons import usage documentation

---

README.md

README.md has old page link.
We can not access to http://gorangajic.github.io/react-icons/ , so I think we should replace the url as http://react-icons.github.io/react-icons/)
```
$ wget -S --spider http://gorangajic.github.io/react-icons/
Spider mode enabled. Check if remote file exists.
--2018-06-15 16:36:40--  http://gorangajic.github.io/react-icons/
Resolving gorangajic.github.io... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to gorangajic.github.io|185.199.108.153|:80... connected.
HTTP request sent, awaiting response... 
HTTP/1.1 404 Not Found
Server: GitHub.com
Content-Type: text/html; charset=utf-8
ETag: "59429d6e-239c"
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
X-GitHub-Request-Id: …
```

Replace github pages url

---

README.md

Just updating Dependabot from v2 to v3 and was confused by the import in this example. Further down the README, in the migrating section, there's an example with the correct syntax, so I realised this one is a typo.
Thanks for `react-icons`!

Fix import in first README example for v3

---

packages/react-icons/.gitignore
packages/react-icons/package.json
packages/react-icons/plugin/defaultImportConverter.js
yarn.lock

- error occurs when processing it as ES Module with Webpack@4.16
- actual: `import { * as React } from 'react';
- expect: `import React from 'react';`
- ↑ is not allowed in ts
- create a babel-plugin and apply only to esmodule
```
ERROR in ./node_modules/react-icons/lib/iconContext.mjs 8:25-44
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
@ ./node_modules/react-icons/lib/iconBase.mjs
@ ./node_modules/react-icons/fa/index.mjs
@ ./src/App.js
@ ./src/index.js
```

fix 'Can't import the named export'

---

README.md

Since this project requires a specific Webpack configuration prioritizing `.mjs` files, and that configuration is not (yet) standard across most, large bundle size will be a common issue encountered for newcomers. Therefore, it may be nice to link to this issue in the README where the ES6 imports are recommended.
This PR adds a change to the README pointing users to that issue, in the section where the old format and new format are compared.
Related to https://github.com/react-icons/react-icons/issues/154

Add link to bundle size issue in README

---

README.md

Add a link to the documentation page from the README. 
Add further example for how to import icon from other package. 
Clean up markdown lint errors. 
Closes #192

chore: Add link to documentation from Readme. lint cleanup.

---

packages/react-icons/src/iconBase.tsx

- Added ternary to line 35 of `iconBase.tsx` to account for an `undefined` className
Fixes #189

Fixed undefined showing up in className.

---

packages/react-icons/scripts/build.js

- fix #199
- erroneously removed the fill: none in feather icon

not remove `fill: none`

---

packages/react-icons/src/iconBase.tsx

https://github.com/react-icons/react-icons/issues/224
Adds default `xmlns` value to all svgs - can still be overridden though as needed. See Issue for details on why.

fix(iconBase): added xmlns to support renderToString

---

packages/demo/src/App.js
packages/demo/src/__snapshots__/App.test.js.snap
packages/react-icons/src/iconBase.tsx
packages/react-icons/src/iconContext.tsx

Added `title` props support.
https://github.com/react-icons/react-icons/issues/228

feat(props): 228: Added title props.

---

packages/react-icons/package.json

The `react-icons` package requires `react` (in `iconBase.tsx`) but doesn't list it in its peer dependencies.
This diff fixes it by adding the missing dependency.

Adds react to the peer dependencies

---

README.md

I noticed that this was added in [v3.7.0](https://github.com/react-icons/react-icons/releases/tag/v3.7.0) but not yet reflected in the README.

Add title props to README

---

README.md

It seems to me that the netlify website is not anymore and I see that the official url next to the Description has been changed too. We should update netlify references from Readme to point to the new location.
I had the netlify URL bookmarked and I did not notice that there are new Icons already and also the web is different.

Update netlify links to github.io

---

packages/react-icons/src/iconBase.tsx

The previous typing required the `attr` to be there, even though it is defined as undefined. By making it optional it is truly an optional property and does not have to be defined when consuming the component.

Fix typing issue

---

packages/react-icons/src/iconBase.tsx

When use the `size` property to change icon size, the `size` attribute is set to svg element like this.
But the `size` attribute is not allowed on svg element, so this PR changes not to set the `size` attribute to svg element.

Change not to set the size attribute to svg element

---

packages/preview/next.config.js
packages/preview/src/components/@core/icon/index.tsx
packages/preview/src/components/@core/sidebar/index.tsx
packages/preview/src/components/pages/search/index.tsx
packages/preview/src/components/pages/search/search-iconset.tsx
packages/preview/src/pages/search.tsx
packages/preview/src/styles/_components.scss

- Fix the problems with the base path (404 after refreshing page). I'm not sure it's the best way to do it, but you can check the result after `BASE_PATH=/react-icons NODE_ENV=production yarn build` in the demo.
- Add search url query param with persistence.
- Added highlighting of matches in the search.
https://gabrii.github.io/react-icons/search?q=react

Preview search fixes and enhancements

---

packages/react-icons/src/icons/index.js

Some remix icons don't suffix with `line` or `fill`, like all of those in [Editor](https://remixicon.com/#edito) category ([git link](https://github.com/Remix-Design/RemixIcon/tree/master/icons/Editor)). As a result, they're currently omitted from `react-icons`

Include Remix Icons without fill/line suffix

---

packages/preview/src/components/@core/code-block/index.tsx
packages/preview/src/components/pages/icons/iconset-import.tsx
packages/preview/src/pages/index.tsx

On the `react-icons` preview website (https://react-icons.github.io/react-icons/) the home page code blocks for containing `npm install react-icons --save` and `npm install @react-icons/all-files --save` are highlighted using a jsx syntax highlighter instead of shell/bash. 
**Current Highlighting**
**Proposed Highlighting**

Fix syntax highlighting for shell/bash code blocks

---

.gitmodules
README.md
packages/react-icons/VERSIONS
packages/react-icons/src/icons/index.js

[Tabler icons](https://github.com/tabler/tabler-icons) is one of the popular icon packs having stars more than 11k.
- **Icon count:** 1978
- **License:** [MIT](https://opensource.org/licenses/MIT)
Close #558.

Add Tabler icons

---

.gitmodules
README.md
packages/react-icons/VERSIONS
packages/react-icons/src/icons/index.js

This MR adds support for HeroIcons version 2.0.8, @nolanleung can you please take a look? thanks :smile:

Add Heroicons 2

---

packages/preview/src/components/@core/sidebar/index.tsx

It might be worth while, but adding some input attributes that would prevent spell checks and auto corrections.
When using the search field I found it difficult to quickly search and sort when my queries were auto-corrected. Neither are super helpful or this use case and it may improve the experience forcing them not to check and/or correct.
I realize this behavior is different on every machine and user. Applying these fixed attributes would help make that behavior between users and environments more consistent.

Avoid auto correction and spell checks

---

packages/preview/src/pages/_document.tsx

the favicon path should be [https://react-icons.github.io/react-icons/favicon.png](https://react-icons.github.io/react-icons/favicon.png)
but currently the link is not valid:

favicon.png relative path

---

.gitmodules
README.md
packages/react-icons/VERSIONS
packages/react-icons/src/icons/index.js

This PR adds the themify icons - Closes #245
Usage
`import { TfiAgenda } from "react-icons/tfi";`
[Themify icons homepage](http://themify.me/themify-icons)
[Themify icons repository](https://github.com/lykmapipo/themify-icons)

ADD: themify icons

---

.gitmodules
README.md
packages/react-icons/VERSIONS
packages/react-icons/src/icons/index.js

Icons library with 285 icons.  You can find additional features on [circumicons.com](https://circumicons.com/), like building arrays, copying individual component tags, etc.

Add Circum icons

---

packages/react-icons/scripts/logics.ts

This PR fixes the new errors caused by hero icons 2 (`Invalid ARIA attribute ariaHidden. Did you mean aria-hidden.`) by non converting the `aria-*` attributes names to camel case.
cc: @kamijin-fanta

Fix converting aria-* attribute names to camel case

---

packages/react-icons/scripts/task_common.ts

The current VERSION file is shown well in the [release notes](https://github.com/react-icons/react-icons/releases/tag/v4.6.0), but [Renovate](https://www.mend.io/free-developer-tools/renovate/) in my repository could not show it well.
|[release notes](https://github.com/react-icons/react-icons/releases/tag/v4.6.0)|Renovate PR|
|-|-|
|![image](https://user-images.githubusercontent.com/7846521/196728042-398e7ff4-db50-45fc-8f83-9413ef655ced.png)|![image](https://user-images.githubusercontent.com/7846521/196728222-72fa7dc5-9a87-4601-9a24-5b2df0fcc437.png)|
So, I'll fix the format of table.

Change versions table format

---

packages/react-icons/src/icons/index.ts

The previous commit was from Oct 2, 2021 
New release: https://github.com/simple-icons/simple-icons/releases/tag/8.5.0

Update Simple Icons to the last release (v8.5.0)

---

packages/react-icons/VERSIONS
packages/react-icons/package.json
packages/react-icons/src/icons/index.ts
yarn.lock

Add Lucide icons, updated version of https://github.com/react-icons/react-icons/pull/602.
@kamijin-fanta I pushed an updated version of [an older PR](https://github.com/react-icons/react-icons/pull/602) which hopefully unblocks getting this shipped. Adding these will make a whole bunch of folks' life easier 🙏🏼 ❤️

Add Lucide icons

---

.github/workflows/nodejs.yml

Failed to get yarn cache in Node.js CI.
https://github.com/react-icons/react-icons/actions/runs/4539744631/jobs/7999901702#step:6:1
We can get yarn cache using only actions/setup-node ([FYI](https://github.com/actions/setup-node/tree/a9893b0cfb0821c9c7b5fec28a6a2e6cdd5e20a4#caching-global-packages-data)). So I remove yarn-cache step, and use `cache` option in setup-node.

Fix: yarn cache in GitHub Actions

---

packages/react-icons/VERSIONS
packages/react-icons/src/icons/index.ts

This pull request contains additional BoxIcon variants, `Solid` & `Logo`. 
Naming convention examples
Regular:    ```
<BiShield />
```
Logo:    ```
<BiLogoTiktok />
```
Solid:    ```
<BiSolidShield />
```
The `Regular` icons are left as is, to avoid breaking changes

Feature: additional variants for BoxIcons (Solid/Logo)

---

packages/react-icons/VERSIONS
packages/react-icons/src/icons/index.ts

Fontawesome 6 is the lastest version why not add it next to the old one ?
- Icon count: 2020
- Licence: CC BY 4.0 License
- Prefix: Fa6
preview: 
Next major release: rename Fa -> Fa5 and Fa6 -> Fa ?

feat: add fontawesome 6

---

packages/preview-astro/src/styles/_components.scss

Addresses the responsiveness issue of the import code text in the icon details modal on smaller screens. The problem was reported in issue  #849 
- Modified the CSS in `.icon-detail-modal-content` to ensure proper responsiveness.
@kamijin-fanta @gorangajic  Could you please review this pull request?

Fix: Resolve Import Code Text Responsiveness in Icon Details Modal on Smaller Screens

---

packages/preview-astro/src/components/icondetailmodal.tsx

Code" in the sense of "computer code" is a mass noun, so this removes the extra S.

Fix Grammatical Error

---

packages/react-icons/scripts/task_common.ts

fix #948 
modify the type definitions to enhance compatibility with `tsc` and fix the error that occurs when `compilerOptions.moduleResolution` in `tsconfig.json` is set to `"bundler"`.

support moduleResolution: bundler in tsconfig

---

packages/preview-astro/src/components/search/index.tsx

fix #468 
"I've addressed the request to decrease the minimum search query length to 2. @kamijin-fanta @gorangajic, could you please review the change?
Previously, the search functionality required a minimum of 3 characters, which limited users' ability to search for shorter terms. With the update, the minimum query length is now 2 characters, allowing for more flexible and efficient searches."

min search length changed to 2

---

packages/preview-astro/src/components/search/search-iconset.tsx

- close #986 
- If there are two consecutive spaces, all items match. In this case, nothing should be displayed.
- If the number of items to be displayed is large, the browser may take a long time to load. Only 100 items will be displayed for each icon set.

preview: Reduce the number of results displayed in search results

---

packages/react-icons/src/iconBase.tsx

React 19 requires ReactNode type as component output to remove linting errors in Typescript, end results are the same.

[React 19] Update IconType type to return React.ReactNode
